// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7HRDMznqojdBNlW6rq2az09LlptDL8xI',
    appId: '1:885008732583:web:6fc2917c167855fa35a682',
    messagingSenderId: '885008732583',
    projectId: 'godawg-964a9',
    authDomain: 'godawg-964a9.firebaseapp.com',
    storageBucket: 'godawg-964a9.appspot.com',
    measurementId: 'G-PJ7XHL4PBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASBY0l3e6Ql-w4MQPCyl9w8kAWzdCE0Ec',
    appId: '1:885008732583:android:8e30730d99f7c11c35a682',
    messagingSenderId: '885008732583',
    projectId: 'godawg-964a9',
    storageBucket: 'godawg-964a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk577foSaSJiZMy66SEw2cN8pxUW-VKeg',
    appId: '1:885008732583:ios:e3eff82f8a952a2d35a682',
    messagingSenderId: '885008732583',
    projectId: 'godawg-964a9',
    storageBucket: 'godawg-964a9.appspot.com',
    iosClientId: '885008732583-f277d4p8htvqfsnfhqk0kgj2vpnq5nmc.apps.googleusercontent.com',
    iosBundleId: 'com.example.goDawg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk577foSaSJiZMy66SEw2cN8pxUW-VKeg',
    appId: '1:885008732583:ios:e3eff82f8a952a2d35a682',
    messagingSenderId: '885008732583',
    projectId: 'godawg-964a9',
    storageBucket: 'godawg-964a9.appspot.com',
    iosClientId: '885008732583-f277d4p8htvqfsnfhqk0kgj2vpnq5nmc.apps.googleusercontent.com',
    iosBundleId: 'com.example.goDawg',
  );
}
